import type { Employee, LeaveRequest, LetterRequest, Notification, User } from "@/types/hr";

export const demoUsers: User[] = [
  {
    id: "user-hrd",
    name: "Rina HRD",
    email: "hrd@demo.com",
    role: "HRD",
  },
  {
    id: "user-budi",
    name: "Budi Santoso",
    email: "budi@demo.com",
    role: "EMPLOYEE",
    employeeId: "emp-001",
  },
];

export const employees: Employee[] = [
  {
    id: "emp-001",
    userId: "user-budi",
    nik: "EMP-001",
    name: "Budi Santoso",
    email: "budi@demo.com",
    department: "Engineering",
    position: "Frontend Developer",
    managerName: "Agus Pratama",
    joinDate: "2024-01-15",
    leaveBalance: 10,
    status: "Aktif",
  },
  {
    id: "emp-002",
    userId: "user-sari",
    nik: "EMP-002",
    name: "Sari Wulandari",
    email: "sari@demo.com",
    department: "People Ops",
    position: "HR Generalist",
    managerName: "Rina HRD",
    joinDate: "2023-08-01",
    leaveBalance: 8,
    status: "Aktif",
  },
  {
    id: "emp-003",
    userId: "user-dimas",
    nik: "EMP-003",
    name: "Dimas Putra",
    email: "dimas@demo.com",
    department: "Sales",
    position: "Account Executive",
    managerName: "Maya Lestari",
    joinDate: "2022-11-20",
    leaveBalance: 6,
    status: "Aktif",
  },
  {
    id: "emp-004",
    userId: "user-lina",
    nik: "EMP-004",
    name: "Lina Kartika",
    email: "lina@demo.com",
    department: "Finance",
    position: "Finance Analyst",
    managerName: "Hendra Wijaya",
    joinDate: "2025-02-10",
    leaveBalance: 11,
    status: "Probation",
  },
];

export const leaveRequests: LeaveRequest[] = [
  {
    id: "LV-2026-0001",
    employeeId: "emp-001",
    employeeName: "Budi Santoso",
    startDate: "2026-07-08",
    endDate: "2026-07-09",
    duration: 2,
    reason: "Urusan keluarga",
    status: "PENDING",
    createdAt: "2026-07-01",
  },
  {
    id: "LV-2026-0002",
    employeeId: "emp-002",
    employeeName: "Sari Wulandari",
    startDate: "2026-07-15",
    endDate: "2026-07-15",
    duration: 1,
    reason: "Medical checkup",
    status: "APPROVED",
    createdAt: "2026-06-28",
  },
  {
    id: "LV-2026-0003",
    employeeId: "emp-003",
    employeeName: "Dimas Putra",
    startDate: "2026-07-20",
    endDate: "2026-07-22",
    duration: 3,
    reason: "Liburan keluarga",
    status: "REJECTED",
    createdAt: "2026-06-25",
  },
];

export const letterRequests: LetterRequest[] = [
  {
    id: "LET-2026-0001",
    employeeId: "emp-001",
    employeeName: "Budi Santoso",
    letterType: "Surat Keterangan Kerja",
    purpose: "Pengajuan visa",
    status: "APPROVED",
    createdAt: "2026-06-22",
    fileUrl: "#",
  },
  {
    id: "LET-2026-0002",
    employeeId: "emp-002",
    employeeName: "Sari Wulandari",
    letterType: "Surat Penghasilan",
    purpose: "KPR",
    status: "PENDING",
    createdAt: "2026-06-30",
  },
  {
    id: "LET-2026-0003",
    employeeId: "emp-003",
    employeeName: "Dimas Putra",
    letterType: "Surat Magang",
    purpose: "Administrasi kampus",
    status: "PENDING",
    createdAt: "2026-07-01",
  },
];

export const notifications: Notification[] = [
  {
    id: "notif-001",
    userId: "user-budi",
    title: "Cuti menunggu approval",
    message: "Pengajuan cuti LV-2026-0001 menunggu approval.",
    type: "leave",
    isRead: false,
    createdAt: "2026-07-01",
  },
  {
    id: "notif-002",
    userId: "user-budi",
    title: "Surat berhasil diajukan",
    message: "Surat keterangan kerja berhasil diajukan.",
    type: "letter",
    isRead: false,
    createdAt: "2026-06-22",
  },
  {
    id: "notif-003",
    userId: "user-budi",
    title: "Cuti disetujui",
    message: "Pengajuan cuti disetujui HRD.",
    type: "approval",
    isRead: false,
    createdAt: "2026-06-20",
  },
  {
    id: "notif-004",
    roleTarget: "HRD",
    title: "Request cuti baru",
    message: "Budi mengajukan cuti.",
    type: "leave",
    isRead: false,
    createdAt: "2026-07-01",
  },
  {
    id: "notif-005",
    roleTarget: "HRD",
    title: "Request surat baru",
    message: "Sari meminta surat keterangan kerja.",
    type: "letter",
    isRead: true,
    createdAt: "2026-06-30",
  },
];
